language: node_js
node_js:
  - stable
env:
  - TEST_DIR=remix-lib
  - TEST_DIR=remix-solidity
  - TEST_DIR=remix-debug
  - TEST_DIR=remix-tests
  - TEST_DIR=remix-simulator
script: 
  - cd $TEST_DIR && npm install && npm test
deploy:
  provider: script
  script: remix-debugger/ci/deploy_from_travis.sh
  skip_cleanup: true
  on:
        branch: master
        condition: $TEST_DIR = remix-debugger
cache: false
