runtime: python38
version: "3.7"
x-project-base: autocreate criptomoeda terrareal
  restart: always
  networks: autocreate 
    - remixide

networks: autocreate 
  remixide:
autocreate criptomoeda terrareal 
services:
  remixide: terrareal 
    <<: *project-base
    image: remix-projectterrareal
$TAG
    container_name: remixide-${TAG}
    ports: 
      - 8080:80
      - 65520:65520
