name: remix-publish-action
on:
  pull_request:
    types: [ labeled ]
description: Publish Remix IDE
inputs:
  token:
    description: 'GitHub auth token'
    default: ${{ github.token }}
author: yann@ethereum.org
jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
     - run: npm install
     - run: nx build remix-ide --with-deps
     - run: node ./apps/remix-ide/ci/publishIpfs
